### ISSUE TITLE
Use of --ci results in error when CIEND is missing in variant info

### ISSUE THREAD

**Issue by ManavalanG** [fakedrtom/SVAFotate#6]
SVAFotate ran into the error below when it was run with a manta vcf and option `--ci out`.

```
Gathering SV coordinates from VCF file: data/raw/in.vcf

Traceback (most recent call last):
  File "/data/user/manag/.conda/envs/test_svafotate/bin/svafotate", line 8, in <module>
    sys.exit(main())
  File "/data/user/manag/.conda/envs/test_svafotate/lib/python3.8/site-packages/svafotate/__main__.py", line 41, in main
    args.func(parser, args)
  File "/data/user/manag/.conda/envs/test_svafotate/lib/python3.8/site-packages/svafotate/svafotate_main.py", line 626, in annotate
    end += int(ciend[1]) if args.ci == "out" else int(ciend[0]) if args.ci == "in" else 0
TypeError: 'NoneType' object is not subscriptable
```

Variant records in Manta vcf don't always contain `CIPOS` and `CIEND`. It might include both, either or none. However, it appears SVAFotate expects them to be always present, and it ran into the error above when the variant included CIPOS but not CIEND. Here is the variant:

```
chr1	934064	MantaDEL:134427:0:1:0:0:0	AGG...	A	275	PASS	END=934904;SVTYPE=DEL;SVLEN=-840;CIGAR=1M840D;CIPOS=0,27;HOMLEN=27;HOMSEQ=GGGGAGGCGGCTGCGTTACAGGTGGGC	GT:FT:GQ:PL:PR:SR	0/1:PASS:132:325,0,129:10,12:1,5
```

When I included `CIEND=0,0`, SVAFotate was able to process the record successfully.

PS - Glad that we met briefly at ACMG :)

**Comment by fakedrtom** [comment]
Hey thanks for reaching out and for trying out SVAFotate. You are correct, if you use the `--ci` option, SVAFotate will expect both CIPOS and CIEND in the INFO field for each variant. If one or both are not present in a variant, you should get the error that you reported. The solution for the time being is to do as you did and make sure you've added an empty `CIPOS=0,0` and/or `CIEND=0,0` to your INFO fields. When I use Manta output, I often use a "doctor_manta.py" script that does this. I will look and see if I can't patch the code to insert these fields if missing when using `--ci`. Thanks!

**Comment by aFienemann** [comment]
Would you mind sharing the Skript you are using as a workaround? I am running into similar problems with my VCFs right now. Thanks!

**Comment by fakedrtom** [comment]
Sorry for my delay. There are a few ways that you might go about doing this, but here is an example of a short python script that uses cyvcf2 to accomplish this:

```
import sys
import cyvcf2
from cyvcf2 import Writer

vcf = cyvcf2.VCF(sys.argv[1])
output_vcf = sys.argv[2]

vcf.add_info_to_header({'ID': 'CIPOS', 'Description': 'Confidence interval around POS for imprecise variants', 'Type': 'Integer', 'Number': '2'})
vcf.add_info_to_header({'ID': 'CIEND', 'Description': 'Confidence interval around END for imprecise variants', 'Type': 'Integer', 'Number': '2'})

def convert_variant(v):
    set_cis_prs(v)

def split_ci(ci):
    return[int(ci.split(',')[0]),  int(ci.split(',')[1])]

def set_cis_prs(v):
    cipos='0,0'
    ciend='0,0'
    if v.INFO.get('CIPOS') is not None:# in v.info:
        cipos=v.INFO.get('CIPOS')
        cipos = str(cipos[0]) + ',' + str(cipos[1])
        [start, stop]=split_ci(cipos)
    if v.INFO.get('CIEND') is not None:# in v.info:
        ciend=v.INFO.get('CIEND')
        ciend = str(ciend[0]) + ',' + str(ciend[1])
        [start, stop]=split_ci(ciend)
    v.INFO['CIPOS']=cipos
    v.INFO['CIEND']=ciend

new_vcf = Writer(output_vcf, vcf)
for v in vcf:
    convert_variant(v)
    new_vcf.write_record(v)
```
